# -*- coding: utf-8 -*-
"""Deployment_Recommendation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19IhQCwKFN4FKRduAJnHe8jtm4Y-dfcVa

# **Streamlit App**
"""

#! pip install streamlit

# streamlit app

import pandas as pd
import numpy as np
import streamlit as st
import pickle
from sklearn.metrics import pairwise_distances

#Reading movies_list data
music_app=open('music_list.pkl',mode='rb')
music=pickle.load(music_app)
music_app.close()

# Reading "similarity_data" which is cosine similarities..
# Due to large data file it is not reading properly.So because of it we have to perform cosine similarities again manually.

# cosine similarity
similarity=1-pairwise_distances(music.iloc[:,1:],metric='cosine')
similarity_array=pd.DataFrame(similarity)
similarity_array=similarity_array.to_numpy()
np.fill_diagonal(similarity_array, 0)
similarity_df=pd.DataFrame(similarity_array)

# fuction recommendation
def recommand(song):
  if song in music['track_name'].values:
    index=music[music['track_name']==song].index[0]
    values=sorted(list(enumerate(similarity_df[index])),reverse=True,key=lambda music:music[1])
    recommendations= [music.iloc[i[0]].track_name for i in values[0:11]]
    return recommendations
  else:
    return []

#title
st.title('Song Recommender Engine')

# Display a select box with all songs
input_method = st.radio("**Choose input method:**", ["Text Input", "Select Box"])

st.subheader("Enter or Select a song name to get similar song recommendations")
if input_method=="Text Input":
    user_song=st.text_input("**Entered Song:**")
elif input_method=="Select Box":
    user_song=st.selectbox("**Selected Song:**",music['track_name'])

#condition
if st.button('recommend'):
  if user_song:
    recommend_songs=recommand(user_song)
    if recommend_songs:
      st.write('Top Recommended Results')
      for song in recommend_songs:
        st.write(f"- {song}")
    else:
      st.write('OOPS!... No recommendation for this song')
      st.write('Please enter valid song')
  else:
    st.write("Please enter a song.")



